Traceback (most recent call last):
  File "C:\Users\romer\Server\cgi-bin\end.py", line 63, in <module>
    shutil.move(text_pre_path,fin_path)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 542, in move
    raise Error("Destination path '%s' already exists" % real_dst)
shutil.Error: Destination path 'C:\Users\romer\Server\work\fin\371113_22500BZX00422000_A_02_01.PDF.txt' already exists
